# Exploring the training data set for stage 2

In [2]:
import pandas as pd

In [4]:
labels = [f'feature{x}' for x in range(1, 785)]
labels.insert(0, 'label')
df = pd.read_csv('../../data/stage_2_data/train.csv', names=labels)

In [5]:
df.head(10)

label  feature1  feature2  feature3  feature4  feature5  feature6  \
0      5         0         0         0         0         0         0   
1      0         0         0         0         0         0         0   
2      4         0         0         0         0         0         0   
3      1         0         0         0         0         0         0   
4      9         0         0         0         0         0         0   
5      2         0         0         0         0         0         0   
6      1         0         0         0         0         0         0   
7      3         0         0         0         0         0         0   
8      1         0         0         0         0         0         0   
9      4         0         0         0         0         0         0   

   feature7  feature8  feature9  ...  feature775  feature776  feature777  \
0         0         0         0  ...           0           0           0   
1         0         0         0  ...           0           0           0   
2         0         0         0  ...           0           0           0   
3         0         0         0  ...           0           0           0   
4         0         0         0  ...           0           0           0   
5         0         0         0  ...           0           0           0   
6         0         0         0  ...           0           0           0   
7         0         0         0  ...           0           0           0   
8         0         0         0  ...           0           0           0   
9         0         0         0  ...           0           0           0   

   feature778  feature779  feature780  feature781  feature782  feature783  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   
5           0           0           0           0           0           0   
6           0           0           0           0           0           0   
7           0           0           0           0           0           0   
8           0           0           0           0           0           0   
9           0           0           0           0           0           0   

   feature784  
0           0  
1           0  
2           0  
3           0  
4           0  
5           0  
6           0  
7           0  
8           0  
9           0  

[10 rows x 785 columns]

# Feature Exploration and Torch utilization

In [6]:
import torch
import numpy as np

In [7]:
# Total size of the features
print(df.loc[0, :])
t1 = torch.tensor(df.loc[0,:])
t1.size(dim=-1)

label         5
feature1      0
feature2      0
feature3      0
feature4      0
             ..
feature780    0
feature781    0
feature782    0
feature783    0
feature784    0
Name: 0, Length: 785, dtype: int64


785

In [8]:
# Build a tensor for the first entru
tensorData = torch.from_numpy(np.asarray(df.loc[0, :]))
print(tensorData.size())
tensorData

torch.Size([785])


tensor([  5,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  

In [20]:
# First column for label
Y = df['label'].to_numpy().reshape([1, -1])
print(Y)
print(Y.shape)

[[5 0 4 ... 5 6 8]]
(1, 60000)


In [19]:
# and 60000 rows
X = df.iloc[:, 1:].to_numpy().T
print(X)
print(X.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(784, 60000)
